"""add new columns

Revision ID: 093ee8c09038
Revises: 
Create Date: 2025-08-20 01:07:13.237486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093ee8c09038'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('task_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_editable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('is_editable')
        batch_op.drop_column('task_minute')
        batch_op.drop_column('task_hour')

    # ### end Alembic commands ###
